In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("twitter_st.csv")
df

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [6]:
%pip install mtranslate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mtranslate
  Downloading mtranslate-1.8.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mtranslate
  Building wheel for mtranslate (setup.py) ... done
  Created wheel for mtranslate: filename=mtranslate-1.8-py3-none-any.whl size=3671 sha256=a066268890803dd77304615fb1b5a6bd34d63413340b51fd756873c14ed83b93
  Stored in directory: /root/.cache/pip/wheels/c2/04/15/d7654c2c4a9a52e09922967593f3278fed66059be65ca671ea
Successfully built mtranslate
Installing collected packages: mtranslate
Successfully installed mtranslate-1.8

In [7]:
from tqdm import tqdm
from mtranslate import translate

translated_tweets = []

for tweet in tqdm(df['tweet']):
    translated_tweet = translate(tweet, 'pt', 'en')
    translated_tweets.append(translated_tweet)

df['tweets_pt'] = translated_tweets
df.to_csv('Dados/twitter_trad.csv', index=False)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 24783/24783 [1:30:27<00:00,  4.57it/s]

In [8]:
df

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,tweets_pt
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,"!!! RT @mayasolovely: Como mulher, vocÃª nÃ£o de..."
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,!!!!! RT @mleew17: menino dats frio ... tyga d...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,!!!!!!! RT @UrKindOfBrand Cara!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,!!!!!!!!!! RT @C_G_Anderson: @viva_based ela p...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,!!!!!!!!!!!!! RT @ShenikaRoberts: A merda que ...
...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,vocÃª Ã© um filho da puta na mentira &#8220;@Lif...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an...","vocÃª foi e quebrou o coraÃ§Ã£o errado, baby, e m..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...,jovem fanfarrÃ£o quer comer !! .. esse mano com...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies,vocÃª tem cadelas selvagens contando mentiras
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,~~Babado | Ntac Eileen Dahlia - Linda combinaÃ§...

In [ ]:
# from google.colab import drive

# drive.mount('/content/drive')
# df.to_csv('/content/drive/My Drive/AIpp/games.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).